In [6]:
import pandas as pd
import numpy as np
data_file = pd.read_csv('/Users/miafusco/Documents/LaunchCode/data-analysis-projects2/cleaning-data-with-pandas/studio/san-fransisco_9-24-2016_9-30-2017.csv')

In [9]:
data_file.head()

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,SAN FRANCISCO,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,155.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
1,PUMPKINS,SAN FRANCISCO,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,10/01/2016,155.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
2,PUMPKINS,SAN FRANCISCO,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,10/01/2016,155.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,PUMPKINS,SAN FRANCISCO,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,10/01/2016,135.0,135.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,PUMPKINS,SAN FRANCISCO,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,10/08/2016,135.0,150.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [12]:
for col in data_file.columns:
    pct_missing = np.mean(data_file[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))

Commodity Name - 0%
City Name - 0%
Type - 78%
Package - 0%
Variety - 0%
Sub Variety - 61%
Grade - 100%
Date - 0%
Low Price - 0%
High Price - 0%
Mostly Low - 0%
Mostly High - 0%
Origin - 0%
Origin District - 100%
Item Size - 75%
Color - 72%
Environment - 100%
Unit of Sale - 100%
Quality - 100%
Condition - 100%
Appearance - 100%
Storage - 100%
Crop - 100%
Repack - 0%
Trans Mode - 100%

In [17]:

total_cells = np.product(data_file.shape)

missing_cells = pd.isnull(data_file).sum()

total_missing = missing_cells.sum()

percentage_missing = round((total_missing/total_cells), 2) *100

print(percentage_missing, "% Missing cells from the data")

AttributeError: module 'numpy' has no attribute 'product'

In [21]:
# Repack Column
data_file["Repack"] = data_file["Repack"].replace({"N":False})
#Check status with a quick head check
data_file.head(3)

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,SAN FRANCISCO,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,155.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
1,PUMPKINS,SAN FRANCISCO,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,10/01/2016,155.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
2,PUMPKINS,SAN FRANCISCO,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,10/01/2016,155.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN

In [28]:
# Fill the Missing Values in the Type Column
data_file["Type"] = data_file["Type"].fillna("Conventional")
print(type)
print(data_file.Type)

<class 'type'>
0      Conventional
1      Conventional
2      Conventional
3      Conventional
4      Conventional
           ...
161    Conventional
162    Conventional
163    Conventional
164    Conventional
165    Conventional
Name: Type, Length: 166, dtype: object

In [34]:
data_file = data_file.drop(["Grade"], axis=1)

KeyError: "['Grade'] not found in axis"

In [32]:
data_file.shape

(166, 24)

In [35]:
data_file.head()

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Date,Low Price,High Price,Mostly Low,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,SAN FRANCISCO,Conventional,24 inch bins,HOWDEN TYPE,NaN,09/24/2016,155.0,155.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
1,PUMPKINS,SAN FRANCISCO,Conventional,24 inch bins,HOWDEN TYPE,NaN,10/01/2016,155.0,155.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
2,PUMPKINS,SAN FRANCISCO,Conventional,24 inch bins,HOWDEN TYPE,NaN,10/01/2016,155.0,155.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
3,PUMPKINS,SAN FRANCISCO,Conventional,24 inch bins,HOWDEN TYPE,NaN,10/01/2016,135.0,135.0,135.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN
4,PUMPKINS,SAN FRANCISCO,Conventional,24 inch bins,HOWDEN TYPE,NaN,10/08/2016,135.0,150.0,135.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN

In [37]:
data_file = data_file.drop(["Trans Mode"], axis=1)

KeyError: "['Trans Mode'] not found in axis"

In [40]:
data_file= ['Date'].value_counts().plot.bar()

AttributeError: 'list' object has no attribute 'value_counts'

In [41]:
data_file['Date'].hist(bins=100)
plt.xticks(rotation=90)

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.